# -*- coding: utf-8 -*-

type_dict = {
    'STRING':'VARCHAR',
    'SMALLINT':'SMALLINT',
    'INTEGER':'INT',
    'WORD':'INT',
    'BOOLEAN':'BOOLEAN',
    'FLOAT':'REAL',
    'CURRENCY':'DECIMAL',
    'BCD':'BYTEA',
    'FMTBCD':'BYTEA',
    'DATE':'DATE',
    'TIME':'TIME',
    'DATETIME':'TIMESTAMP',
    'TIMESTAMP':'TIMESTAMP',
    'BYTES':'SMALLINT[]',
    'VARBYTES':'SMALLINT[]',
    'BLOB':'BYTEA[]',
    'MEMO':'TEXT[]',
    'GRAPHIC':'BYTEA',
    'FMTMEMO':'TEXT[]',
    'FIXEDCHAR':'CHAR',
    'WIDESTRING':'VARCHAR',
    'LARGEINT':'INT8',
    'COMP':'INT8',
    'ARRAY':'ARRAY[]',
    'FIXEDWIDECHAR':'CHAR',
    'WIDEMEMO':'TEXT[]',
    'CODE':'TEXT',
    'RECORDID':'INT',
    'SET':'ARRAY[]',
    'PERIOD':'INTERVAL',
    'BYTE':'BYTEA'
}
